apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - istio/01-base.yaml
  - istio/02-istiod.yaml
  - istio/03-ingress.yaml
  - observability/prometheus.yaml
  - observability/kiali.yaml
  - observability/jaeger.yaml
  - observability/grafana.yaml
  - argocd-ingress-policy.yaml

namespace: istio-system
